name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: movies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          trivy-version: latest

      - name: Cache Trivy vulnerability DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: Run Trivy filesystem scan
        run: |
          trivy fs . \
            --format table \
            --output trivy-report.txt || true

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: movies/trivy-report.txt
