name: Laravel PHP Security & Docker Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, zip
          coverage: none

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # Install Trivy CLI
      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.66.0
          trivy --version

      # Restore Trivy DB cache
      - name: Restore Trivy DB cache
        uses: actions/cache@v4
        with:
          path: .cache/trivy
          key: trivy-db-${{ runner.os }}-v1
          restore-keys: |
            trivy-db-${{ runner.os }}-

      # Scan PHP dependencies - JSON
      - name: Scan PHP dependencies (composer.lock)
        run: |
          mkdir -p trivy-reports
          trivy fs . \
            --security-checks vuln \
            --ignore-unfixed \
            --format json \
            --output trivy-reports/php-deps.json || true

      # Convert JSON to HTML Table (for PHP dependencies)
      - name: Convert PHP JSON to HTML Table
        uses: Teebra/JSON-to-HTML-table@v2.0.0
        with:
          json-file: ./trivy-reports/php-deps.json

      # Upload HTML Table artifact (PHP dependencies)
      - name: Upload PHP HTML Table to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-deps-html
          path: output.html

      # Build Docker image
      - name: Build Docker image
        run: docker build -t laravel-movies:latest .

      # Scan Docker image - JSON
      - name: Scan Docker image
        run: |
          mkdir -p trivy-reports
          trivy image laravel-movies:latest \
            --security-checks vuln \
            --ignore-unfixed \
            --format json \
            --output trivy-reports/docker-image.json || true

      # Convert Docker JSON to HTML Table
      - name: Convert Docker JSON to HTML Table
        uses: Teebra/JSON-to-HTML-table@v2.0.0
        with:
          json-file: ./trivy-reports/docker-image.json

      # Upload HTML Table artifact (Docker image)
      - name: Upload Docker HTML Table to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-html
          path: output.html

      # Save Docker image as artifact
      - name: Save Docker image as artifact
        run: |
          mkdir -p artifacts
          docker save laravel-movies:latest -o artifacts/laravel-movies.tar

      # Upload Docker image artifact
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: artifacts/laravel-movies.tar
