name: Laravel PHP Security & Docker Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, zip
          coverage: none

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # Install Trivy CLI
      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.66.0
          trivy --version

      # Restore Trivy DB cache
      - name: Restore Trivy DB cache
        uses: actions/cache@v4
        with:
          path: .cache/trivy
          key: trivy-db-${{ runner.os }}-v1
          restore-keys: |
            trivy-db-${{ runner.os }}-

      # Scan PHP dependencies - JSON & HTML
      - name: Scan PHP dependencies (composer.lock)
        run: |
          mkdir -p trivy-reports
          # JSON report
          trivy fs . \
            --security-checks vuln \
            --ignore-unfixed \
            --format json \
            --output trivy-reports/php-deps.json || true
          # HTML report
          trivy fs . \
            --security-checks vuln \
            --ignore-unfixed \
            --format template \
            --template "@contrib/html.tpl" \
            --output trivy-reports/php-deps.html || true

      # Build Docker image
      - name: Build Docker image
        run: docker build -t laravel-movies:latest .

      # Scan Docker image - JSON & HTML
      - name: Scan Docker image
        run: |
          mkdir -p trivy-reports
          # JSON report
          trivy image laravel-movies:latest \
            --security-checks vuln \
            --ignore-unfixed \
            --format json \
            --output trivy-reports/docker-image.json || true
          # HTML report
          trivy image laravel-movies:latest \
            --security-checks vuln \
            --ignore-unfixed \
            --format template \
            --template "@contrib/html.tpl" \
            --output trivy-reports/docker-image.html || true

      # Upload Trivy reports (JSON + HTML)
      - name: Upload Trivy reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/*

      # Save Docker image as artifact
      - name: Save Docker image as artifact
        run: |
          mkdir -p artifacts
          docker save laravel-movies:latest -o artifacts/laravel-movies.tar

      # Upload Docker image artifact
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: artifacts/laravel-movies.tar
