name: Trivy Full Security Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install Trivy CLI
      - name: Install Trivy CLI (official installer)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin v0.66.0
          trivy --version

      # 3️⃣ Restore Trivy DB cache (speeds up scan)
      - name: Restore Trivy DB cache
        uses: actions/cache@v4
        with:
          path: .cache/trivy
          key: trivy-db-${{ runner.os }}-v1
          restore-keys: |
            trivy-db-${{ runner.os }}-

      # 4️⃣ Run full filesystem scan (all code + dependencies)
      - name: Run Trivy filesystem scan (JSON)
        run: |
          mkdir -p .cache/trivy
          trivy fs . \
            --cache-dir $(pwd)/.cache/trivy \
            --format json \
            --output trivy-filesystem-report.json

      # 5️⃣ Run IaC (Infrastructure-as-Code) scan (Terraform/Docker/K8s)
      - name: Run Trivy IaC misconfiguration scan (JSON)
        run: |
          mkdir -p .cache/trivy
          trivy config . \
            --format json \
            --output trivy-iac-report.json

      # 6️⃣ Debug workspace (optional, verify files exist)
      - name: Debug - list workspace files
        run: ls -R .

      # 7️⃣ Upload filesystem scan report as artifact
      - name: Upload filesystem scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-filesystem-report
          path: trivy-filesystem-report.json

      # 8️⃣ Upload IaC scan report as artifact
      - name: Upload IaC scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-report
          path: trivy-iac-report.json
