name: Trivy Scan (action - filesystem)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy filesystem scan (action)
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          # IMPORTANT: tell the action to do a filesystem scan and where to scan
          scan-type: fs
          scan-ref: ./movies          # path to scan (relative to repo root)
          format: table
          output: movies/trivy-report.txt
          cache-dir: /github/workspace/.cache/trivy
          # severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL    # optional
          # ignore-unfixed: true                          # optional
        # ensure report uploads even if vulnerabilities are found:
        continue-on-error: true

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: movies/trivy-report.txt
