name: Trivy Scan (CLI)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-cli-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy CLI (official installer)
        run: |
          # Pin a Trivy CLI version (change v0.66.0 if you prefer)
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin v0.66.0
          trivy --version

      - name: Restore Trivy DB cache
        uses: actions/cache@v4
        with:
          path: .cache/trivy
          key: trivy-db-${{ runner.os }}-v1
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Run Trivy filesystem scan (movies/) in JSON format
        run: |
          mkdir -p .cache/trivy
          mkdir -p movies
          trivy fs ./movies \
            --cache-dir $(pwd)/.cache/trivy \
            --format json \
            --output movies/trivy-report.json || true

      - name: Debug - list workspace files
        if: always()
        run: ls -R .

      - name: Upload Trivy scan report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: movies/trivy-report.json
